export default [{
  name: 'name',
  label: 'Название',
  field: 'name',
  required: true,
  align: 'left',
  sortable: false
}, {
  name: 'language',
  label: 'Язык',
  field: 'language',
  required: true,
  align: 'left',
  sortable: false
}, {
  name: 'html_url',
  label: 'Ссылка',
  field: 'html_url',
  required: true,
  align: 'left',
  sortable: false
}, {
  name: 'description',
  label: 'Описание',
  field: 'description',
  required: true,
  align: 'left',
  sortable: false
}]
